# Generated by Django 5.2 on 2025-04-16 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('image',
                 models.ImageField(
                     max_length=255,
                     upload_to='store/product')),
                ('product',
                 models.ForeignKey(
                     default=None,
                     on_delete=django.db.models.deletion.CASCADE,
                     to='store.product')),
            ],
            options={
                'verbose_name': 'Product Gallery',
                'verbose_name_plural': 'Product Gallery',
            },
        ),
    ]
