# Generated by Django 5.2 on 2025-04-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts',
         '0003_alter_userprofile_address_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(
                blank=True,
                default='userprofile/user-logo.png',
                upload_to='userprofile/'),
        ),
    ]
