# Generated by Django 5.2 on 2025-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignCouponEntry',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Assign Coupons',
                'managed': False,
            },
        ),
    ]
