# Generated by Django 5.2 on 2025-04-18 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_assigncouponentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('code', 'user')},
        ),
    ]
