# Generated by Django 5.2 on 2025-04-18 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_coupon_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coupon', unique_together=set(), ), migrations.AddConstraint(
            model_name='coupon', constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('used', False)), fields=(
                        'code', 'user'), name='unique_active_coupon_per_user'), ), ]
