# Generated by Django 5.2 on 2025-04-18 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_coupon_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCoupon',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('code',
                 models.CharField(
                     max_length=50,
                     unique=True)),
                ('discount_percent',
                 models.PositiveIntegerField(
                     validators=[
                         django.core.validators.MinValueValidator(1),
                         django.core.validators.MaxValueValidator(60)])),
                ('is_active',
                 models.BooleanField(
                     default=True)),
            ],
            options={
                'verbose_name': 'GeneralCoupon',
                'verbose_name_plural': 'GeneralCoupon',
            },
        ),
    ]
