# Generated by Django 5.2 on 2025-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderproduct_color_remove_orderproduct_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(
                blank=True,
                help_text="Data format: {'tax_type':{'tax_percentage':'tax_amount'}}",
                null=True),
        ),
    ]
