# Generated by Django 5.2 on 2025-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='net_total',
            field=models.FloatField(null=True),
        ),
    ]
