# Generated by Django 5.2 on 2025-04-18 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_generalcoupon_created_at_generalcoupon_updated_at_and_more"),
        ("orders", "0008_order_net_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="general_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.generalcoupon",
            ),
        ),
    ]
